### ISSUE TITLE
How to create a Secret during rancher-vcluster init? [Question]

### ISSUE THREAD

**Issue by ER-EPR** [harvester/experimental-addons#6]
Hi, @bk201 @guangbochen @ibrokethecloud 
I want to use DNS01 challenge for the rancher-vcluster SSL certificate. But I haven't been successful in creating a secret for DNS provider credentials. I tried to put the yaml in manifest or manifestTemplate besides rancher and cert-manager configuration. But no secret is created during installation of the addon. I have to manually add the secret after the installation. And if I add the code before other helm install yaml code, the following code won't be execute either. So I think there is something wrong with the yaml code I wrote, but I can not find any Docs about it.

```
manifests: |-
        apiVersion: helm.cattle.io/v1
        kind: Secret
        metadata:
          name: namecheap-credentials
          namespace: cert-manager
        type: Opaque
        stringData:
          apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          apiUser: xxxxxx
```

Is it about the "stringData" not supported here? Do I have to use "data" and manually convert the content to base64? Or do I have to create a helm chart to deploy the secret, not directly?
